# Generated by Django 6.1.1 on 2026-09-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_note_date_and_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='blurb',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='medication',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='medication',
            name='drug_class',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
