# Generated by Django 6.1.1 on 2026-09-09 21:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on-time', 'On time'), ('late', 'Late'), ('edited', 'Edited'), ('missed', 'Missed')], default='on-time', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doses', to='tracker.medication')),
            ],
            options={
                'ordering': ['-date', '-taken_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='tracker_dos_user_id_37a02b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_selections', to='tracker.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-selected_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_medication_per_user')],
            },
        ),
    ]
