# Generated by Django 6.1.1 on 2026-09-10 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_seed_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='pk_components',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medication',
            name='retrieved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='medication',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usermedication',
            name='scheduled_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
