"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default):
    """Read a boolean from the environment. Anything in the truthy set counts
    as True; everything else (including an empty value) is False."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default):
    """Read a comma-separated list from the environment, ignoring blanks."""
    raw = os.environ.get(name)
    if raw is None:
        return list(default)
    return [item.strip() for item in raw.split(",") if item.strip()]


# Everything below that differs between a laptop and the web VM is driven by
# an environment variable, with a default that keeps `manage.py runserver`
# working out of the box. provisions/web.sh sets these in the gunicorn unit.

# SECURITY WARNING: keep the secret key used in production secret! The
# fallback is a development-only key -- set DJANGO_SECRET_KEY on the VM.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-#o9==s8(c(@4scbi)yr-$5vpi5%+$n43^)t&qw@!2a8tyd$1+-',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

# Django refuses to serve with DEBUG off and an empty ALLOWED_HOSTS, so the
# default covers localhost plus the web VM's private-network address.
ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    ['localhost', '127.0.0.1', '192.168.56.12', 'web'],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'users',
    'tracker'
]

# Send credentials with request. The SPA runs on a different origin to the
# API in both deployments -- Vite's dev server on a laptop (localhost:5173)
# and the built frontend served from the web VM (192.168.56.12) -- so both
# have to be trusted for the session cookie and CSRF token to survive.
CORS_ALLOW_CREDENTIALS = True

_DEFAULT_FRONTEND_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://192.168.56.12:5173",
    "http://192.168.56.12:8000",
]

CORS_ALLOWED_ORIGINS = env_list('DJANGO_CORS_ORIGINS', _DEFAULT_FRONTEND_ORIGINS)
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_ORIGINS', CORS_ALLOWED_ORIGINS)

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# The db VM (192.168.56.10) runs postgres; provisions/db.sh creates the
# `adhd` database and role, and Django migrations own the schema. Credentials
# come from the environment so nothing secret lives in the repo.
#
# Set DB_ENGINE=sqlite for local development or to run the test suite on a
# laptop with no postgres and no VMs:
#
#     DB_ENGINE=sqlite py manage.py test
#
DB_ENGINE = os.environ.get('DB_ENGINE', 'postgresql')

if DB_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'adhd'),
            'USER': os.environ.get('DB_USER', 'adhd'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', '192.168.56.10'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

# Hashing a password with the default PBKDF2 settings takes about a second,
# which the auth tests do dozens of times. Under `manage.py test` only, drop
# to a fast hasher -- it takes the suite from minutes to seconds and never
# affects a real deployment.
if 'test' in sys.argv:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-NZ'

LANGUAGES = [
    ("en-NZ", "English (New Zealand)")
]
 
TIME_ZONE = 'Pacific/Auckland'
 
USE_I18N = True
 
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Where `manage.py collectstatic` gathers the admin's static files for
# gunicorn to serve on the web VM. Ignored by `runserver`, which serves them
# straight out of each app.
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# The pk service: a stateless calculator on the private network, reachable
# only from this VM. web never does the release-curve or adherence maths
# itself -- it fetches parameters from the database and posts them here.
# Overridable so local dev (this venv has no VM) can point at a locally-run
# pk instance instead of the deployed 192.168.56.11.
PK_SERVICE_URL = os.environ.get('PK_SERVICE_URL', 'http://192.168.56.11:8001')
PK_SERVICE_TIMEOUT = float(os.environ.get('PK_SERVICE_TIMEOUT', '5'))

"""
# Authenticate user using UserAccount table
AUTH_USER_MODEL = "users.UserAccount"
 
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}
"""
